//===----------------------------------------------------------------------===//
//
//                                  tinyOS
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//	Copyright (C) 2023, Is This On? Holdings Ltd
//
//  Harry Moulton <me@h3adsh0tzz.com>
//
//===----------------------------------------------------------------------===//

#ifndef __TBOOT_CONF_H__
#define __TBOOT_CONF_H__

/* This file is auto-generated by CMake and scripts under conf/ */

#define TBOOT_BUILD_NAME                "tBoot"
#define TBOOT_BUILD_VERSION             "tboot-1041.74.0.1"
#define TBOOT_BUILD_STYLE               "Debug"
#define TBOOT_BUILD_TARGET              "aarch64-virt"

#endif /* __tboot_conf_h__ */